image:
  repository: abuchijoe/complete-devops-project
  tag: a7a26cd
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false