image:
  repository: abuchijoe/complete-devops-project
  tag: da5d457
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
httpRoute:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false