---

name: Complete Devops Project Pipeline

on:
  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push to ECR
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/complete-devops-project:${{ env.SHORT_SHA }}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Configure Git Author
        run: |
          git config --local user.email "peemijoe9522@gmail.com"
          git config --local user.name "Joseph-peemi"

      - name: Update Helm Chart with new Image tag
        run: |
          sed -i "s|repository:.*|repository: ${{ steps.login-ecr.outputs.registry }}/complete-devops-project|" ./complete-devops-project-time-printer/values.yaml
          sed -i 's/tag:.*/tag: "'"$SHORT_SHA"'"/' ./complete-devops-project-time-printer/values.yaml
          git add ./complete-devops-project-time-printer/values.yaml
          git commit -m "Updated image tag to ${{ env.SHORT_SHA }}"
          git push --no-verify https://${{ secrets.GITHUB_TOKEN }}@github.com/Joseph-peemi/complete-devops-project.git
